name: Build Website and Check Links
description: Builds a Jekyll Website and verifies the links inside it

inputs:
  url_ignore:
    required: false
    description: The list of regex urls to ignore
    default: ""
  file_ignore:
    required: false
    description: The list of files to ignore
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Build Jekyll Site
      shell: bash
      run: |
        bundle install
        bundle exec jekyll build

    - name: Test links
      uses: docker://klakegg/html-proofer:3.16.0
      with:
        args: >-
          --allow-hash-href
          --check-html
          --empty-alt-ignore
          --http-status-ignore 302,401
          --file-ignore "${{ inputs.file_ignore }}"
          --url-ignore "${{ inputs.url_ignore }}"
          ./_site

