name: Build Website and Check Links
description: Builds a Jekyll Website and verifies the links inside it

inputs:
  input_file:
    required: false
    description: A yaml file with with the
  url_ignore:
    required: false
    description: The list of regex urls to ignore
    default: ""
  file_ignore:
    required: false
    description: The list of files to ignore
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Build Jekyll Site
      shell: bash
      run: |
        bundle install
        bundle exec jekyll build


    - name: Test links
      uses: docker://hub.opensciencegrid.org/opensciencegrid/html-proofer:latest
      with:
        args: >-
          --ignore-empty-alt 
          --ignore-missing-alt 
          --no-enforce-https 
          --no-check-external-hash 
          --ignore-status-codes 302,401
          --ignore-files "${{ inputs.file_ignore }}"
          --ignore-urls "${{ inputs.url_ignore }}"
          ./_site

